# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service as ChromeService


class TestFarmaco():
    def setup_method(self, method):
        self.driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_farmaco(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.set_window_size(1936, 1056)
        self.driver.find_element(By.LINK_TEXT, "Farmaci").click()
        self.driver.find_element(By.ID, "manufacturer").click()
        dropdown = self.driver.find_element(By.ID, "manufacturer")
        dropdown.find_element(By.XPATH, "//option[. = 'Sciroppo']").click()
        element = self.driver.find_element(By.ID, "prezzo")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).click_and_hold().perform()
        element = self.driver.find_element(By.ID, "prezzo")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.ID, "prezzo")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).release().perform()
        self.driver.find_element(By.ID, "prezzo").send_keys("31")
        self.driver.find_element(By.ID, "prezzo").click()
        self.driver.find_element(By.CSS_SELECTOR, ".bg-blue-600").click()

        assert self.driver.current_url=="http://127.0.0.1:5000/farmacia/filtroCatalogo"